"""
validate.py

This script performs data quality validations on processed financial
datasets generated by transform.py.

Input folder:
- data/processed/

Validation output:
- Prints validation results in the terminal.
- Saves validation summary to data/validation/validation_summary.csv.
- Saves failed record details to data/validation/validation_details.csv.
"""

from pathlib import Path
import pandas as pd


# -------------------------------------------------------------------
# Project paths
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parents[1]
PROCESSED_DATA_DIR = BASE_DIR / "data" / "processed"
VALIDATION_DATA_DIR = BASE_DIR / "data" / "validation"

VALIDATION_DATA_DIR.mkdir(parents=True, exist_ok=True)


# -------------------------------------------------------------------
# Validation result containers
# -------------------------------------------------------------------

validation_summary: list[dict] = []
validation_details: list[pd.DataFrame] = []


# -------------------------------------------------------------------
# Helper functions
# -------------------------------------------------------------------

def read_processed_csv(filename: str) -> pd.DataFrame:
    """Read a processed CSV file from the processed data folder."""
    file_path = PROCESSED_DATA_DIR / filename

    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    return pd.read_csv(file_path)


def print_section(title: str) -> None:
    """Print a formatted section title for validation results."""
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)


def register_validation_result(
    check_name: str,
    dataset_name: str,
    status: str,
    records_failed: int,
    description: str,
    failed_records: pd.DataFrame | None = None
) -> None:
    """
    Register validation result in summary and optionally store failed records.

    This function centralizes how validation outcomes are recorded.
    It allows every validation function to follow the same reporting structure.
    """
    validation_summary.append({
        "check_name": check_name,
        "dataset_name": dataset_name,
        "status": status,
        "records_failed": records_failed,
        "description": description,
    })

    print(f"{status}: {description}")

    if failed_records is not None and not failed_records.empty:
        detail_df = failed_records.copy()
        detail_df.insert(0, "dataset_name", dataset_name)
        detail_df.insert(0, "check_name", check_name)
        validation_details.append(detail_df)


def save_validation_outputs() -> None:
    """Save validation summary and failed record details to CSV files."""
    summary_df = pd.DataFrame(validation_summary)

    summary_output_path = VALIDATION_DATA_DIR / "validation_summary.csv"
    details_output_path = VALIDATION_DATA_DIR / "validation_details.csv"

    summary_df.to_csv(summary_output_path, index=False, encoding="utf-8")

    if validation_details:
        details_df = pd.concat(validation_details, ignore_index=True)
    else:
        details_df = pd.DataFrame(columns=[
            "check_name",
            "dataset_name",
            "message"
        ])

    details_df.to_csv(details_output_path, index=False, encoding="utf-8")

    print("\nValidation output files created:")
    print(f"- {summary_output_path}")
    print(f"- {details_output_path}")


# -------------------------------------------------------------------
# Generic validation functions
# -------------------------------------------------------------------

def check_missing_values(df: pd.DataFrame, dataset_name: str) -> None:
    """Check missing values by column."""
    check_name = "Missing Values Check"
    print_section(f"{check_name} - {dataset_name}")

    missing_values = df.isna().sum()
    missing_values = missing_values[missing_values > 0]

    if missing_values.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description="No missing values found."
        )
    else:
        failed_records = (
            missing_values
            .reset_index()
            .rename(columns={"index": "column_name", 0: "missing_count"})
        )

        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(failed_records),
            description="Missing values found in one or more columns.",
            failed_records=failed_records
        )


def check_duplicates(
    df: pd.DataFrame,
    dataset_name: str,
    key_columns: list[str]
) -> None:
    """Check duplicated records based on selected key columns."""
    check_name = "Duplicate Check"
    print_section(f"{check_name} - {dataset_name}")

    duplicated_records = df[df.duplicated(subset=key_columns, keep=False)]

    if duplicated_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description=f"No duplicates found based on {key_columns}."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(duplicated_records),
            description=f"Duplicate records found based on {key_columns}.",
            failed_records=duplicated_records
        )


def check_allowed_values(
    df: pd.DataFrame,
    dataset_name: str,
    column: str,
    allowed_values: list[str]
) -> None:
    """Check that a column only contains expected categorical values."""
    check_name = "Allowed Values Check"
    print_section(f"{check_name} - {dataset_name}.{column}")

    invalid_records = df[~df[column].isin(allowed_values)]

    if invalid_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description=f"All values in {column} are valid."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(invalid_records),
            description=f"Invalid values found in {column}.",
            failed_records=invalid_records
        )


def check_positive_values(
    df: pd.DataFrame,
    dataset_name: str,
    column: str
) -> None:
    """Check that selected numeric column has positive values."""
    check_name = "Positive Value Check"
    print_section(f"{check_name} - {dataset_name}.{column}")

    invalid_records = df[df[column] <= 0]

    if invalid_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description=f"All values in {column} are positive."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(invalid_records),
            description=f"Non-positive values found in {column}.",
            failed_records=invalid_records
        )


def check_non_negative_values(
    df: pd.DataFrame,
    dataset_name: str,
    column: str
) -> None:
    """Check that selected numeric column has non-negative values."""
    check_name = "Non-Negative Value Check"
    print_section(f"{check_name} - {dataset_name}.{column}")

    invalid_records = df[df[column] < 0]

    if invalid_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description=f"All values in {column} are non-negative."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(invalid_records),
            description=f"Negative values found in {column}.",
            failed_records=invalid_records
        )


def check_referential_integrity(
    child_df: pd.DataFrame,
    parent_df: pd.DataFrame,
    child_column: str,
    parent_column: str,
    relationship_name: str
) -> None:
    """Check that child table keys exist in the parent table."""
    check_name = "Referential Integrity Check"
    print_section(f"{check_name} - {relationship_name}")

    invalid_records = child_df[
        ~child_df[child_column].isin(parent_df[parent_column])
    ]

    if invalid_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=relationship_name,
            status="PASS",
            records_failed=0,
            description=f"All {child_column} values exist in parent table."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=relationship_name,
            status="WARNING",
            records_failed=len(invalid_records),
            description=f"Invalid foreign keys found in {child_column}.",
            failed_records=invalid_records
        )


# -------------------------------------------------------------------
# Business rule validations
# -------------------------------------------------------------------

def check_payment_dates_after_disbursement(
    payments: pd.DataFrame,
    loans: pd.DataFrame
) -> None:
    """Check that payment dates are not before loan disbursement dates."""
    check_name = "Payment Date After Disbursement Date Check"
    dataset_name = "payments_loans"
    print_section(check_name)

    merged_df = payments.merge(
        loans[["loan_id", "disbursement_date"]],
        on="loan_id",
        how="left"
    )

    merged_df["payment_date"] = pd.to_datetime(
        merged_df["payment_date"],
        errors="coerce"
    )

    merged_df["disbursement_date"] = pd.to_datetime(
        merged_df["disbursement_date"],
        errors="coerce"
    )

    invalid_records = merged_df[
        merged_df["payment_date"] < merged_df["disbursement_date"]
    ]

    if invalid_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description="All payment dates are on or after disbursement dates."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(invalid_records),
            description="Payments before disbursement date found.",
            failed_records=invalid_records
        )


def check_missed_payments_have_zero_amount(payments: pd.DataFrame) -> None:
    """Check that missed payments have zero payment amount."""
    check_name = "Missed Payments Have Zero Amount Check"
    dataset_name = "payments"
    print_section(check_name)

    invalid_records = payments[
        (payments["payment_status"] == "Missed")
        & (payments["payment_amount"] != 0)
    ]

    if invalid_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description="All missed payments have zero payment amount."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(invalid_records),
            description="Missed payments with non-zero amount found.",
            failed_records=invalid_records
        )


def check_paid_payments_have_zero_days_late(payments: pd.DataFrame) -> None:
    """Check that paid payments are not late."""
    check_name = "Paid Payments Have Zero Days Late Check"
    dataset_name = "payments"
    print_section(check_name)

    invalid_records = payments[
        (payments["payment_status"] == "Paid")
        & (payments["days_late"] != 0)
    ]

    if invalid_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description="All paid payments have zero days late."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(invalid_records),
            description="Paid payments with days_late greater than zero found.",
            failed_records=invalid_records
        )


def check_late_payments_have_positive_days_late(payments: pd.DataFrame) -> None:
    """Check that late payments have days_late greater than zero."""
    check_name = "Late Payments Have Positive Days Late Check"
    dataset_name = "payments"
    print_section(check_name)

    invalid_records = payments[
        (payments["payment_status"] == "Late")
        & (payments["days_late"] <= 0)
    ]

    if invalid_records.empty:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="PASS",
            records_failed=0,
            description="All late payments have positive days late."
        )
    else:
        register_validation_result(
            check_name=check_name,
            dataset_name=dataset_name,
            status="WARNING",
            records_failed=len(invalid_records),
            description="Late payments with zero or negative days_late found.",
            failed_records=invalid_records
        )


# -------------------------------------------------------------------
# Main validation process
# -------------------------------------------------------------------

def main() -> None:
    print("Starting data quality validation process...")

    customers = read_processed_csv("customers_processed.csv")
    branches = read_processed_csv("branches_processed.csv")
    advisors = read_processed_csv("advisors_processed.csv")
    products = read_processed_csv("products_processed.csv")
    loans = read_processed_csv("loans_processed.csv")
    payments = read_processed_csv("payments_processed.csv")

    # Missing values
    check_missing_values(customers, "customers")
    check_missing_values(branches, "branches")
    check_missing_values(advisors, "advisors")
    check_missing_values(products, "products")
    check_missing_values(loans, "loans")
    check_missing_values(payments, "payments")

    # Duplicate checks
    check_duplicates(customers, "customers", ["customer_id"])
    check_duplicates(branches, "branches", ["branch_id"])
    check_duplicates(advisors, "advisors", ["advisor_id"])
    check_duplicates(products, "products", ["product_id"])
    check_duplicates(loans, "loans", ["loan_id"])
    check_duplicates(payments, "payments", ["payment_id"])

    # Allowed categorical values
    check_allowed_values(customers, "customers", "gender", ["F", "M"])
    check_allowed_values(
        customers,
        "customers",
        "customer_segment",
        ["Individual", "Small Business", "Microenterprise"]
    )
    check_allowed_values(loans, "loans", "loan_status", ["Active", "Closed", "Delinquent"])
    check_allowed_values(payments, "payments", "payment_status", ["Paid", "Late", "Missed"])

    # Numeric validations
    check_positive_values(loans, "loans", "loan_amount")
    check_positive_values(loans, "loans", "loan_term_months")
    check_non_negative_values(products, "products", "interest_rate")
    check_non_negative_values(payments, "payments", "payment_amount")
    check_non_negative_values(payments, "payments", "days_late")

    # Referential integrity validations
    check_referential_integrity(
        loans,
        customers,
        "customer_id",
        "customer_id",
        "loans.customer_id -> customers.customer_id"
    )

    check_referential_integrity(
        loans,
        products,
        "product_id",
        "product_id",
        "loans.product_id -> products.product_id"
    )

    check_referential_integrity(
        loans,
        branches,
        "branch_id",
        "branch_id",
        "loans.branch_id -> branches.branch_id"
    )

    check_referential_integrity(
        loans,
        advisors,
        "advisor_id",
        "advisor_id",
        "loans.advisor_id -> advisors.advisor_id"
    )

    check_referential_integrity(
        advisors,
        branches,
        "branch_id",
        "branch_id",
        "advisors.branch_id -> branches.branch_id"
    )

    check_referential_integrity(
        payments,
        loans,
        "loan_id",
        "loan_id",
        "payments.loan_id -> loans.loan_id"
    )

    # Business rule validations
    check_payment_dates_after_disbursement(payments, loans)
    check_missed_payments_have_zero_amount(payments)
    check_paid_payments_have_zero_days_late(payments)
    check_late_payments_have_positive_days_late(payments)

    save_validation_outputs()

    print("\nData quality validation process completed.")


if __name__ == "__main__":
    main()  