
"""
validate.py

This script performs data quality validations on processed financial
datasets generated by transform.py.

Input folder:
- data/processed/

Validation output:
- Prints validation results in the terminal.
"""

from pathlib import Path
import pandas as pd


# -------------------------------------------------------------------
# Project paths
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parents[1]
PROCESSED_DATA_DIR = BASE_DIR / "data" / "processed"


# -------------------------------------------------------------------
# Helper functions
# -------------------------------------------------------------------

def read_processed_csv(filename: str) -> pd.DataFrame:
    """Read a processed CSV file from the processed data folder."""
    file_path = PROCESSED_DATA_DIR / filename

    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    return pd.read_csv(file_path)


def print_section(title: str) -> None:
    """Print a formatted section title for validation results."""
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)


def print_result(status: str, message: str) -> None:
    """Print a standardized validation result."""
    print(f"{status}: {message}")


# -------------------------------------------------------------------
# Generic validation functions
# -------------------------------------------------------------------

def check_missing_values(df: pd.DataFrame, dataset_name: str) -> None:
    """Check missing values by column."""
    print_section(f"Missing Values Check - {dataset_name}")

    missing_values = df.isna().sum()
    missing_values = missing_values[missing_values > 0]

    if missing_values.empty:
        print_result("PASS", "No missing values found.")
    else:
        print_result("WARNING", "Missing values found:")
        print(missing_values)


def check_duplicates(
    df: pd.DataFrame,
    dataset_name: str,
    key_columns: list[str]
) -> None:
    """Check duplicated records based on selected key columns."""
    print_section(f"Duplicate Check - {dataset_name}")

    duplicated_records = df[df.duplicated(subset=key_columns, keep=False)]

    if duplicated_records.empty:
        print_result("PASS", f"No duplicates found based on {key_columns}.")
    else:
        print_result("WARNING", f"Duplicate records found based on {key_columns}:")
        print(duplicated_records)


def check_allowed_values(
    df: pd.DataFrame,
    dataset_name: str,
    column: str,
    allowed_values: list[str]
) -> None:
    """Check that a column only contains expected categorical values."""
    print_section(f"Allowed Values Check - {dataset_name}.{column}")

    invalid_records = df[~df[column].isin(allowed_values)]

    if invalid_records.empty:
        print_result("PASS", f"All values in {column} are valid.")
    else:
        print_result("WARNING", f"Invalid values found in {column}:")
        print(invalid_records)


def check_positive_values(
    df: pd.DataFrame,
    dataset_name: str,
    column: str
) -> None:
    """Check that selected numeric column has positive values."""
    print_section(f"Positive Value Check - {dataset_name}.{column}")

    invalid_records = df[df[column] <= 0]

    if invalid_records.empty:
        print_result("PASS", f"All values in {column} are positive.")
    else:
        print_result("WARNING", f"Non-positive values found in {column}:")
        print(invalid_records)


def check_non_negative_values(
    df: pd.DataFrame,
    dataset_name: str,
    column: str
) -> None:
    """Check that selected numeric column has non-negative values."""
    print_section(f"Non-Negative Value Check - {dataset_name}.{column}")

    invalid_records = df[df[column] < 0]

    if invalid_records.empty:
        print_result("PASS", f"All values in {column} are non-negative.")
    else:
        print_result("WARNING", f"Negative values found in {column}:")
        print(invalid_records)


def check_referential_integrity(
    child_df: pd.DataFrame,
    parent_df: pd.DataFrame,
    child_column: str,
    parent_column: str,
    relationship_name: str
) -> None:
    """Check that child table keys exist in the parent table."""
    print_section(f"Referential Integrity Check - {relationship_name}")

    invalid_records = child_df[
        ~child_df[child_column].isin(parent_df[parent_column])
    ]

    if invalid_records.empty:
        print_result("PASS", f"All {child_column} values exist in parent table.")
    else:
        print_result("WARNING", f"Invalid foreign keys found in {child_column}:")
        print(invalid_records)


# -------------------------------------------------------------------
# Business rule validations
# -------------------------------------------------------------------

def check_payment_dates_after_disbursement(
    payments: pd.DataFrame,
    loans: pd.DataFrame
) -> None:
    """Check that payment dates are not before loan disbursement dates."""
    print_section("Business Rule Check - Payment Date After Disbursement Date")

    merged_df = payments.merge(
        loans[["loan_id", "disbursement_date"]],
        on="loan_id",
        how="left"
    )

    merged_df["payment_date"] = pd.to_datetime(
        merged_df["payment_date"],
        errors="coerce"
    )

    merged_df["disbursement_date"] = pd.to_datetime(
        merged_df["disbursement_date"],
        errors="coerce"
    )

    invalid_records = merged_df[
        merged_df["payment_date"] < merged_df["disbursement_date"]
    ]

    if invalid_records.empty:
        print_result(
            "PASS",
            "All payment dates are on or after disbursement dates."
        )
    else:
        print_result("WARNING", "Payments before disbursement date found:")
        print(invalid_records)


def check_missed_payments_have_zero_amount(payments: pd.DataFrame) -> None:
    """Check that missed payments have zero payment amount."""
    print_section("Business Rule Check - Missed Payments Have Zero Amount")

    invalid_records = payments[
        (payments["payment_status"] == "Missed")
        & (payments["payment_amount"] != 0)
    ]

    if invalid_records.empty:
        print_result("PASS", "All missed payments have zero payment amount.")
    else:
        print_result("WARNING", "Missed payments with non-zero amount found:")
        print(invalid_records)


def check_paid_payments_have_zero_days_late(payments: pd.DataFrame) -> None:
    """Check that paid payments are not late."""
    print_section("Business Rule Check - Paid Payments Have Zero Days Late")

    invalid_records = payments[
        (payments["payment_status"] == "Paid")
        & (payments["days_late"] != 0)
    ]

    if invalid_records.empty:
        print_result("PASS", "All paid payments have zero days late.")
    else:
        print_result("WARNING", "Paid payments with days_late greater than zero found:")
        print(invalid_records)


# -------------------------------------------------------------------
# Main validation process
# -------------------------------------------------------------------

def main() -> None:
    print("Starting data quality validation process...")

    customers = read_processed_csv("customers_processed.csv")
    branches = read_processed_csv("branches_processed.csv")
    advisors = read_processed_csv("advisors_processed.csv")
    products = read_processed_csv("products_processed.csv")
    loans = read_processed_csv("loans_processed.csv")
    payments = read_processed_csv("payments_processed.csv")

    # Missing values
    check_missing_values(customers, "customers")
    check_missing_values(branches, "branches")
    check_missing_values(advisors, "advisors")
    check_missing_values(products, "products")
    check_missing_values(loans, "loans")
    check_missing_values(payments, "payments")

    # Duplicate checks
    check_duplicates(customers, "customers", ["customer_id"])
    check_duplicates(branches, "branches", ["branch_id"])
    check_duplicates(advisors, "advisors", ["advisor_id"])
    check_duplicates(products, "products", ["product_id"])
    check_duplicates(loans, "loans", ["loan_id"])
    check_duplicates(payments, "payments", ["payment_id"])

    # Allowed categorical values
    check_allowed_values(customers, "customers", "gender", ["F", "M"])
    check_allowed_values(
        customers,
        "customers",
        "customer_segment",
        ["Individual", "Small Business", "Microenterprise"]
    )
    check_allowed_values(loans, "loans", "loan_status", ["Active", "Closed", "Delinquent"])
    check_allowed_values(payments, "payments", "payment_status", ["Paid", "Late", "Missed"])

    # Numeric validations
    check_positive_values(loans, "loans", "loan_amount")
    check_positive_values(loans, "loans", "loan_term_months")
    check_non_negative_values(products, "products", "interest_rate")
    check_non_negative_values(payments, "payments", "payment_amount")
    check_non_negative_values(payments, "payments", "days_late")

    # Referential integrity validations
    check_referential_integrity(
        loans,
        customers,
        "customer_id",
        "customer_id",
        "loans.customer_id → customers.customer_id"
    )

    check_referential_integrity(
        loans,
        products,
        "product_id",
        "product_id",
        "loans.product_id → products.product_id"
    )

    check_referential_integrity(
        loans,
        branches,
        "branch_id",
        "branch_id",
        "loans.branch_id → branches.branch_id"
    )

    check_referential_integrity(
        loans,
        advisors,
        "advisor_id",
        "advisor_id",
        "loans.advisor_id → advisors.advisor_id"
    )

    check_referential_integrity(
        advisors,
        branches,
        "branch_id",
        "branch_id",
        "advisors.branch_id → branches.branch_id"
    )

    check_referential_integrity(
        payments,
        loans,
        "loan_id",
        "loan_id",
        "payments.loan_id → loans.loan_id"
    )

    # Business rule validations
    check_payment_dates_after_disbursement(payments, loans)
    check_missed_payments_have_zero_amount(payments)
    check_paid_payments_have_zero_days_late(payments)

    print("\nData quality validation process completed.")


if __name__ == "__main__":
    main()
